<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $guarded = [];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->created_by = auth()->id();
        });
    }

    function user()
    {
        return $this->belongsTo(User::class, 'created_by', 'id');
    }
    function card()
    {
        return $this->belongsTo(Card::class, 'card_id', 'id');
    }
}
